"""Report formatting using Jinja2 templates."""
from jinja2 import Template

REPORT_TEMPLATE_STR = """
# Research Report: {{ company_name }}
**Report Date**: {{ report_date }}
**Run ID**: {{ run_id }}

---

## Executive Summary
{{ synthesis.executive_summary }}

---

## Key Findings
{% for finding in synthesis.key_findings %}
- {{ finding }}
{% endfor %}

---

## Specialist Analysis Summary

### Financial Analysis
{{ specialists.financial_analyst.analysis_text[:800] }}...

### Market Research
{{ specialists.market_researcher.analysis_text[:800] }}...

### News & Sentiment
{{ specialists.news_analyst.analysis_text[:800] }}...

### Risk Assessment
{{ specialists.risk_assessor.analysis_text[:800] }}...

### ESG Analysis
{{ specialists.esg_analyst.analysis_text[:800] }}...

---

## Risk Factors
{% for risk in synthesis.risk_factors %}
- {{ risk }}
{% endfor %}

---

## Strategic Recommendations
{% for rec in synthesis.recommendations %}
{{ loop.index }}. {{ rec }}
{% endfor %}

---

## Compliance & Disclaimers
*Compliance Status: {{ "APPROVED" if compliance.approved else "ISSUES IDENTIFIED" }}*
*Risk Rating: {{ compliance.risk_rating | upper }}*

{% for disclaimer in compliance.required_disclaimers %}
> {{ disclaimer }}
{% endfor %}

---
*This report was generated by Contoso Research System. Chapter 18 of "Prompt to Production" by Maneesh Kumar.*
"""


def render_report(
    company_name: str,
    run_id: str,
    synthesis,
    compliance,
    specialists: dict,
    report_date: str,
) -> str:
    """Render the full research report using the Jinja2 template."""
    template = Template(REPORT_TEMPLATE_STR)
    return template.render(
        company_name=company_name,
        run_id=run_id,
        report_date=report_date,
        synthesis=synthesis,
        compliance=compliance,
        specialists=specialists,
    )
